### ISSUE TITLE
Group Based Permission

### ISSUE THREAD

**Issue by Fordy436** [RHazDev/NetworkSpy#1]
You've made it so a particular Player needs the permissions which is really impractical. You're not even checking if the group they're in has the permission, you're just checking the Player. A lot of Server Owners would like all of their Admins to have the ability to spy on commands, but you're making it extremely hard for Owners because they have to constantly update the Player's permissions when it would be so much easier to add the permission once to a group or inherent group rather than add and remove permissions to specific Players all of the time.

**Comment by hazae41** [comment]
Servers owner can use [LuckPerms](https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/) for group managing

**Comment by Fordy436** [comment]
I do use LuckPerms... and in a LuckPerms group I have your permissions, but your Plugin isn't detecting that those groups have the permissions and therefore it's like the Player doesn't have the permissions.

**Comment by hazae41** [comment]
It works well for me
![](https://image.prntscr.com/image/QgRs4TVuRNqYiLBS5Q_1Gg.png)
